# Generated by Django 4.2.7 on 2025-06-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0006_fixtures'),
    ]

    operations = [
    ]
