# Generated by Django 4.2.7 on 2025-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0006_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alternate_names',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
    ]
