# Generated by Django 4.2.17 on 2025-10-01 15:54
import logging
from django.db import migrations, models
from geonames.models import GeonamesAdm1, GeonamesAdm2, GeonamesAdm3, GeonamesAdm4, GeonamesAdm5, PopulatedPlace
logger = logging.getLogger(__name__)


def update_values(apps, schema_editor):
    try:
        GeonamesAdm1.objects.all().update(suppressed=False)
        GeonamesAdm2.objects.all().update(suppressed=False)
        GeonamesAdm3.objects.all().update(suppressed=False)
        GeonamesAdm4.objects.all().update(suppressed=False)
        GeonamesAdm5.objects.all().update(suppressed=False)
        PopulatedPlace.objects.all().update(suppressed=False)
    except Exception as ex:
        logger.error("fixture_geonames: %s" % str(ex))


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0007_country_alternate_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonamesadm1',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geonamesadm2',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geonamesadm3',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geonamesadm4',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geonamesadm5',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='populatedplace',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_values)

    ]
